/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxCalendarCtrl_WRAP_H_
#define SWIG_WxCalendarCtrl_WRAP_H_

class Swig::Director;


class SwigDirector_wxCalendarCtrl : public wxCalendarCtrl, public Swig::Director {

public:
    SwigDirector_wxCalendarCtrl(VALUE self);
    SwigDirector_wxCalendarCtrl(VALUE self, wxWindow *parent, wxWindowID id, wxDateTime const &date = wxDefaultDateTime, wxPoint const &pos = wxDefaultPosition, wxSize const &size = wxDefaultSize, long style = wxCAL_SHOW_HOLIDAYS|wxWANTS_CHARS, wxString const &name = wxCalendarNameStr);
    virtual ~SwigDirector_wxCalendarCtrl();
};


#endif
