/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxChoice_WRAP_H_
#define SWIG_WxChoice_WRAP_H_

class Swig::Director;


class SwigDirector_wxChoice : public wxChoice, public Swig::Director {

public:
    SwigDirector_wxChoice(VALUE self);
    SwigDirector_wxChoice(VALUE self, wxWindow *parent, wxWindowID id, wxPoint const &pos = wxDefaultPosition, wxSize const &size = wxDefaultSize, int n = 0, wxString const choices[] = NULL, long style = 0, wxValidator const &validator = wxDefaultValidator, wxString const &name = wxChoiceNameStr);
    SwigDirector_wxChoice(VALUE self, wxWindow *parent, wxWindowID id, wxPoint const &pos, wxSize const &size, wxArrayString const &choices, long style = 0, wxValidator const &validator = wxDefaultValidator, wxString const &name = wxChoiceNameStr);
    virtual void Clear();
    virtual int GetCount() const;
    virtual int GetSelection() const;
    virtual ~SwigDirector_wxChoice();
    virtual void Delete(int n);
    virtual void SetSelection(int n);
    virtual int FindString(wxString const &s) const;
    virtual void SetString(int n, wxString const &s);
};


#endif
