/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxMask_WRAP_H_
#define SWIG_WxMask_WRAP_H_

class Swig::Director;


class SwigDirector_wxMask : public wxMask, public Swig::Director {

public:
    SwigDirector_wxMask(VALUE self);
    SwigDirector_wxMask(VALUE self, wxBitmap const &wxbitmap);
    SwigDirector_wxMask(VALUE self, wxBitmap const &wxbitmap, wxColour const &wxcolour);
    SwigDirector_wxMask(VALUE self, wxBitmap const &bitmap, int index);
    virtual ~SwigDirector_wxMask();
};


#endif
