/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.22
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxPen_WRAP_H_
#define SWIG_WxPen_WRAP_H_

class Swig::Director;


class SwigDirector_wxPen : public wxPen, public Swig::Director {

public:
    SwigDirector_wxPen(VALUE self, bool disown = false);
    SwigDirector_wxPen(VALUE self, wxColour const &colour, int width, int style, bool disown = false);
    SwigDirector_wxPen(VALUE self, wxString const &colourName, int width, int style, bool disown = false);
    SwigDirector_wxPen(VALUE self, wxBitmap const &stipple, int width, bool disown = false);
    SwigDirector_wxPen(VALUE self, wxPen const &pen, bool disown = false);
};


#endif
