/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxSingleChoiceDialog_WRAP_H_
#define SWIG_WxSingleChoiceDialog_WRAP_H_

class Swig::Director;


class SwigDirector_wxSingleChoiceDialog : public wxSingleChoiceDialog, public Swig::Director {

public:
    SwigDirector_wxSingleChoiceDialog(VALUE self, wxWindow *parent, wxString const &message, wxString const &caption, int n, wxString const choices[], char **clientData = NULL, long style = wxOK, wxPoint const &pos = wxDefaultPosition);
    virtual ~SwigDirector_wxSingleChoiceDialog();
};


#endif
