/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxWindowDC_WRAP_H_
#define SWIG_WxWindowDC_WRAP_H_

class Swig::Director;


class SwigDirector_wxWindowDC : public wxWindowDC, public Swig::Director {

public:
    SwigDirector_wxWindowDC(VALUE self, wxWindow *window);
    virtual ~SwigDirector_wxWindowDC();
};


#endif
