/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.22
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxWindow_WRAP_H_
#define SWIG_WxWindow_WRAP_H_

class Swig::Director;


class SwigDirector_wxWindow : public wxWindow, public Swig::Director {

public:
    SwigDirector_wxWindow(VALUE self, bool disown = false);
    SwigDirector_wxWindow(VALUE self, wxWindow *parent, wxWindowID id, wxPoint const &pos = wxDefaultPosition, wxSize const &size = wxDefaultSize, long style = 0, wxString const &name = wxPanelNameStr, bool disown = false);
    virtual bool SetForegroundColour(wxColour const &colour);
    virtual bool SetBackgroundColour(wxColour const &colour);
    virtual void ReleaseMouse();
    virtual void CaptureMouse();
    virtual void SetFocusFromKbd();
    virtual void SetFocus();
    virtual bool Reparent(wxWindow *newParent);
    virtual void RemoveChild(wxWindow *child);
    virtual void AddChild(wxWindow *child);
    virtual void SetSize(wxSize const &size);
    virtual void SetClientSize(wxSize const &size);
    virtual bool IsShown() const;
    virtual int GetCharWidth() const;
    virtual int GetCharHeight() const;
    virtual bool HasCapture() const;
    virtual bool IsEnabled() const;
    virtual bool IsRetained() const;
    virtual wxWindow *GetParent() const;
    virtual void SetVirtualSizeHints(int minW, int minH, int maxW = -1, int maxH = -1);
    virtual void SetSizeHints(int minW = -1, int minH = -1, int maxW = -1, int maxH = -1, int incW = -1, int incH = -1);
    virtual void SetSize(int width, int height);
    virtual void SetSize(int x, int y, int width, int height, int sizeFlags = wxSIZE_AUTO);
    virtual void SetClientSize(int width, int height);
    virtual void SetValidator(wxValidator const &validator);
    virtual void SetSize(wxRect const &rect);
    virtual void ScrollWindow(int dx, int dy, wxRect const *rect = NULL);
    virtual void RefreshRect(wxRect const &rect);
    virtual void Refresh(bool eraseBackground = true, wxRect const *rect = NULL);
    virtual void SetAcceleratorTable(wxAcceleratorTable const &accel);
    virtual void GetTextExtent(wxString const &string, int *x, int *y, int *descent = NULL, int *externalLeading = NULL, wxFont const *font = NULL) const;
    virtual void SetWindowStyleFlag(long style);
    virtual bool TransferDataFromWindow();
    virtual void Thaw();
    virtual bool SetCursor(wxCursor const &cursor);
    virtual bool TransferDataToWindow();
    virtual void Freeze();
    virtual void FitInside();
    virtual void Update();
    virtual bool Validate();
    virtual void Fit();
    virtual void ScreenToClient(int *x, int *y) const;
    virtual void ClientToScreen(int *x, int *y) const;
    virtual void GetClientSize(int *width, int *height) const;
    virtual void GetPosition(int *x, int *y) const;
    virtual void GetSize(int *width, int *height) const;
    virtual bool Show(bool show = true);
    virtual void SetThemeEnabled(bool enable);
    virtual void SetScrollPos(int orientation, int pos, bool refresh = true);
    virtual void SetScrollbar(int orientation, int position, int thumbSize, int range, bool refresh = true);
    virtual void MakeModal(bool flag);
    virtual bool Enable(bool enable = true);
    virtual void SetTitle(wxString const &title);
    virtual void SetName(wxString const &name);
    virtual void SetHelpText(wxString const &helpText);
    virtual void DestroyChildren();
    virtual bool ScrollPages(int pages);
    virtual bool ScrollLines(int lines);
    virtual int GetScrollThumb(int orientation);
    virtual int GetScrollPos(int orientation);
    virtual int GetScrollRange(int orientation);
    virtual bool Destroy();
};


#endif
