// wxGrid.h
// This file was automatically generated
// by extractxml.rb, part of the wxRuby project
// Do not make changes directly to this file!

#if !defined(_wxGrid_h_)
#define _wxGrid_h_
class wxGrid : public wxScrolledWindow
{
public:
   wxGrid() ;
   wxGrid(wxWindow*  parent , wxWindowID  id , const wxPoint&  pos = wxDefaultPosition, const wxSize&  size = wxDefaultSize, long  style = wxWANTS_CHARS, const wxString&  name = wxPanelNameStr) ;
  virtual  ~wxGrid() ;
  bool AppendCols(int  numCols = 1, bool  updateLabels = true) ;
  bool AppendRows(int  numRows = 1, bool  updateLabels = true) ;
  void AutoSize() ;
  void AutoSizeColumn(int  col , bool  setAsMin = true) ;
  void AutoSizeColumns(bool  setAsMin = true) ;
  void AutoSizeRow(int  row , bool  setAsMin = true) ;
  void AutoSizeRows(bool  setAsMin = true) ;
  void BeginBatch() ;
  bool CanDragColSize() ;
  bool CanDragRowSize() ;
  bool CanDragGridSize() ;
  bool CanEnableCellControl() const;
  wxRect CellToRect(int  row , int  col ) ;
  wxRect CellToRect(const wxGridCellCoords&  coords ) ;
  void ClearGrid() ;
  void ClearSelection() ;
  bool CreateGrid(int  numRows , int  numCols , wxGrid::wxGridSelectionModes  selmode = wxGrid::wxGridSelectCells) ;
  bool DeleteCols(int  pos = 0, int  numCols = 1, bool  updateLabels = true) ;
  bool DeleteRows(int  pos = 0, int  numRows = 1, bool  updateLabels = true) ;
  void DisableCellEditControl() ;
  void DisableDragColSize() ;
  void DisableDragGridSize() ;
  void DisableDragRowSize() ;
  void EnableCellEditControl(bool  enable = true) ;
  void EnableDragColSize(bool  enable = true) ;
  void EnableDragGridSize(bool  enable = true) ;
  void EnableDragRowSize(bool  enable = true) ;
  void EnableEditing(bool  edit ) ;
  void EnableGridLines(bool  enable = true) ;
  void EndBatch() ;
  void ForceRefresh() ;
  int GetBatchCount() ;
  void GetCellAlignment(int  row , int  col , int*  horiz , int*  vert ) ;
  wxColour GetCellBackgroundColour(int  row , int  col ) ;
  wxGridCellEditor* GetCellEditor(int  row , int  col ) ;
  wxFont GetCellFont(int  row , int  col ) ;
  wxGridCellRenderer* GetCellRenderer(int  row , int  col ) ;
  wxColour GetCellTextColour(int  row , int  col ) ;
  wxString GetCellValue(int  row , int  col ) ;
  wxString GetCellValue(const wxGridCellCoords& coords ) ;
  void GetColLabelAlignment(int*  horiz , int*  vert ) ;
  int GetColLabelSize() ;
  wxString GetColLabelValue(int  col ) ;
  int GetColSize(int  col ) ;
  void GetDefaultCellAlignment(int*  horiz , int*  vert ) ;
  wxColour GetDefaultCellBackgroundColour() ;
  wxFont GetDefaultCellFont() ;
  wxColour GetDefaultCellTextColour() ;
  int GetDefaultColLabelSize() ;
  int GetDefaultColSize() ;
  wxGridCellEditor* GetDefaultEditor() const;
  wxGridCellRenderer* GetDefaultRenderer() const;
  int GetDefaultRowLabelSize() ;
  int GetDefaultRowSize() ;
  int GetGridCursorCol() ;
  int GetGridCursorRow() ;
  wxColour GetGridLineColour() ;
  bool GridLinesEnabled() ;
  wxColour GetLabelBackgroundColour() ;
  wxFont GetLabelFont() ;
  wxColour GetLabelTextColour() ;
  int GetNumberCols() ;
  int GetNumberRows() ;
  void GetRowLabelAlignment(int*  horiz , int*  vert ) ;
  int GetRowLabelSize() ;
  wxString GetRowLabelValue(int  row ) ;
  int GetRowSize(int  row ) ;
  wxGrid::wxGridSelectionModes GetSelectionMode() const;
  wxGridCellCoordsArray GetSelectedCells() const;
  wxArrayInt GetSelectedCols() const;
  wxArrayInt GetSelectedRows() const;
  wxGridCellCoordsArray GetSelectionBlockTopLeft() const;
  wxGridCellCoordsArray GetSelectionBlockBottomRight() const;
  wxGridTableBase * GetTable() const;
  void HideCellEditControl() ;
  bool InsertCols(int  pos = 0, int  numCols = 1, bool  updateLabels = true) ;
  bool InsertRows(int  pos = 0, int  numRows = 1, bool  updateLabels = true) ;
  bool IsCellEditControlEnabled() const;
  bool IsCurrentCellReadOnly() const;
  bool IsEditable() ;
  bool IsInSelection(int  row , int  col ) const;
  bool IsInSelection(const wxGridCellCoords&  coords ) const;
  bool IsReadOnly(int  row , int  col ) const;
  bool IsSelection() ;
  bool IsVisible(int  row , int  col , bool  wholeCellVisible = true) ;
  bool IsVisible(const wxGridCellCoords&  coords , bool  wholeCellVisible = true) ;
  void MakeCellVisible(int  row , int  col ) ;
  void MakeCellVisible(const wxGridCellCoords&  coords ) ;
  bool MoveCursorDown(bool  expandSelection ) ;
  bool MoveCursorLeft(bool  expandSelection ) ;
  bool MoveCursorRight(bool  expandSelection ) ;
  bool MoveCursorUp(bool  expandSelection ) ;
  bool MoveCursorDownBlock(bool  expandSelection ) ;
  bool MoveCursorLeftBlock(bool  expandSelection ) ;
  bool MoveCursorRightBlock(bool  expandSelection ) ;
  bool MoveCursorUpBlock(bool  expandSelection ) ;
  bool MovePageDown() ;
  bool MovePageUp() ;
  void SaveEditControlValue() ;
  void SelectAll() ;
  void SelectBlock(int  topRow , int  leftCol , int  bottomRow , int  rightCol , bool  addToSelected = false) ;
  void SelectBlock(const wxGridCellCoords&  topLeft , const wxGridCellCoords&  bottomRight , bool  addToSelected = false) ;
  void SelectCol(int  col , bool  addToSelected = false) ;
  void SelectRow(int  row , bool  addToSelected = false) ;
  void SetCellAlignment(int  row , int  col , int  horiz , int  vert ) ;
  void SetCellAlignment(int  align , int  row , int  col ) ;
  void SetCellAlignment(int  align ) ;
  void SetCellEditor(int  row , int  col , wxGridCellEditor*  editor ) ;
  void SetCellFont(int  row , int  col , const wxFont&  font ) ;
  void SetCellRenderer(int  row , int  col , wxGridCellRenderer*  renderer ) ;
  void SetCellTextColour(int  row , int  col , const wxColour&  colour ) ;
  void SetCellTextColour(const wxColour&  val , int  row , int  col ) ;
  void SetCellTextColour(const wxColour&  colour ) ;
  void SetCellValue(int  row , int  col , const wxString&  s ) ;
  void SetCellValue(const wxGridCellCoords&  coords , const wxString&  s ) ;
  void SetCellValue(const wxString&  val , int  row , int  col ) ;
  void SetColAttr(int  col , wxGridCellAttr*  attr ) ;
  void SetColFormatBool(int  col ) ;
  void SetColFormatNumber(int  col ) ;
  void SetColFormatFloat(int  col , int  width = -1, int  precision = -1) ;
  void SetColFormatCustom(int  col , const wxString&  typeName ) ;
  void SetColLabelAlignment(int  horiz , int  vert ) ;
  void SetColLabelSize(int  height ) ;
  void SetColLabelValue(int  col , const wxString&  value ) ;
  void SetColMinimalWidth(int  col , int  width ) ;
  void SetColMinimalAcceptableWidth(int  width ) ;
  int GetColMinimalAcceptableWidth() ;
  void SetColSize(int  col , int  width ) ;
  void SetDefaultCellAlignment(int  horiz , int  vert ) ;
  void SetDefaultCellBackgroundColour(const wxColour&  colour ) ;
  void SetDefaultCellFont(const wxFont&  font ) ;
  void SetDefaultEditor(wxGridCellEditor*  editor ) ;
  void SetDefaultRenderer(wxGridCellRenderer*  renderer ) ;
  void SetDefaultColSize(int  width , bool  resizeExistingCols = false) ;
  void SetDefaultRowSize(int  height , bool  resizeExistingRows = false) ;
  void SetGridCursor(int  row , int  col ) ;
  void SetGridLineColour(const wxColour& colour ) ;
  void SetLabelBackgroundColour(const wxColour&  colour ) ;
  void SetLabelFont(const wxFont&  font ) ;
  void SetLabelTextColour(const wxColour&  colour ) ;
  void SetReadOnly(int  row , int  col , bool  isReadOnly = true) ;
  void SetRowAttr(int  row , wxGridCellAttr*  attr ) ;
  void SetRowLabelAlignment(int  horiz , int  vert ) ;
  void SetRowLabelSize(int  width ) ;
  void SetRowLabelValue(int  row , const wxString&  value ) ;
  void SetRowMinimalHeight(int  row , int  height ) ;
  void SetRowMinimalAcceptableHeight(int  height ) ;
  int GetRowMinimalAcceptableHeight() ;
  void SetRowSize(int  row , int  height ) ;
  void SetSelectionMode(wxGrid::wxGridSelectionModes  selmode ) ;
  bool SetTable(wxGridTableBase*  table , bool  takeOwnership = false, wxGrid::wxGridSelectionModes  selmode = wxGrid::wxGridSelectCells) ;
  void ShowCellEditControl() ;
  int XToCol(int  x ) ;
  int XToEdgeOfCol(int  x ) ;
  int YToEdgeOfRow(int  y ) ;
  int YToRow(int  y ) ;
  wxRect BlockToDeviceRect(const wxGridCellCoords &  topLeft , const wxGridCellCoords &  bottomRight ) ;
  wxRect SelectionToDeviceRect() ;
  wxColour GetSelectionBackground() const;
  wxColour GetSelectionForeground() const;
  void SetSelectionBackground(const wxColour&  c ) ;
  void SetSelectionForeground(const wxColour&  c ) ;
  void RegisterDataType(const wxString&  typeName , wxGridCellRenderer*  renderer , wxGridCellEditor*  editor ) ;
  wxGridCellEditor* GetDefaultEditorForCell(int  row , int  col ) const;
  wxGridCellEditor* GetDefaultEditorForCell(const wxGridCellCoords&  c ) const;
  wxGridCellRenderer* GetDefaultRendererForCell(int  row , int  col ) const;
  wxGridCellEditor* GetDefaultEditorForType(const wxString&  typeName ) const;
  wxGridCellRenderer* GetDefaultRendererForType(const wxString&  typeName ) const;
  void SetMargins(int  extraWidth , int  extraHeight ) ;
   wxGrid(wxWindow*  parent , int  x , int  y , int  w = -1, int  h = -1, long  style = wxWANTS_CHARS, const wxString&  name = wxPanelNameStr) ;
  void UpdateDimensions() ;
  int GetRows() ;
  int GetCols() ;
  int GetCursorRow() ;
  int GetCursorColumn() ;
  int GetScrollPosX() ;
  int GetScrollPosY() ;
  void SetScrollX(int  x ) ;
  void SetScrollY(int  y ) ;
  void SetColumnWidth(int  col , int  width ) ;
  int GetColumnWidth(int  col ) ;
  void SetRowHeight(int  row , int  height ) ;
  int GetViewHeight() ;
  int GetViewWidth() ;
  void SetLabelSize(int  orientation , int  sz ) ;
  int GetLabelSize(int  orientation ) ;
  void SetLabelAlignment(int  orientation , int  align ) ;
  int GetLabelAlignment(int  orientation , int  align ) ;
  void SetLabelValue(int  orientation , const wxString&  val , int  pos ) ;
  wxString GetLabelValue(int  orientation , int  pos ) ;
  wxFont GetCellTextFont() const;
  wxFont GetCellTextFont(int  row , int  col ) const;
  void SetCellTextFont(const wxFont&  fnt ) ;
  void SetCellTextFont(const wxFont&  fnt , int  row , int  col ) ;
  void SetCellBackgroundColour(const wxColour&  col ) ;
  void SetCellBackgroundColour(int  row , int  col , const wxColour&  colour ) ;
  void SetCellBackgroundColour(const wxColour&  colour , int  row , int  col ) ;
  bool GetEditable() ;
  void SetEditable(bool  edit = true) ;
  bool GetEditInPlace() ;
  void SetEditInPlace(bool  edit = true) ;
  void SetCellBitmap(wxBitmap*  bitmap , int  row , int  col ) ;
  void SetDividerPen(const wxPen&  pen ) ;
  wxPen& GetDividerPen() const;
  virtual void OnActivate(bool  active ) ;
  void Fit() ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
};


#endif
