require 'rake/packagetask'
require 'rbconfig'

# For building a Debian Package
if (RUBY_PLATFORM =~ /linux/) && ((File.read("/etc/lsb-release") =~ /DISTRIB_ID\=Ubuntu$/) ||
                (File.read("/etc/lsb-release") =~ /DISTRIB_ID\=Debian$/))
        require "rake/rakedeb"
end

# find the file where the version is stored
VERSION_FILE = File.join %w|lib wx_sugar version.rb|

# set the version from the environment variable
if ENV['VERSION']
  WXSUGAR_VERSION = ENV['VERSION']
  File.open(VERSION_FILE, 'w') do | version_file |
    version_file.puts "module WxSugar"
    version_file.puts "  VERSION = '#{WXSUGAR_VERSION}'"
    version_file.puts "end"
  end
# or load the version from the file
elsif File.exists?(VERSION_FILE)
  require VERSION_FILE
  WXSUGAR_VERSION = WxSugar::VERSION
else
  WXSUGAR_VERSION = ''
end

desc "Make a WxSugar gem"
task :gem do
  wxsugar_gemspec = Gem::Specification.new do | s |
    # BASICS
    s.name = 'wx_sugar'
    s.version = WXSUGAR_VERSION
    s.summary = "Syntax extensions for WxRuby."
    s.description = <<-EOF
      Ruby-ifies the ruby API for WxRuby.
    EOF

    # CONTACT
    s.author = "Alex Fenton"
    s.email = "alex@pressure.to"
    s.homepage = "http://www.pressure.to/qda/"
    s.rubyforge_project = "weft-qda"

    # REQUIREMENTS
    s.required_ruby_version = '>= 1.8.1'  

    s.files = FileList[ 'bin/**/*',
                        'lib/**/*', 
                        'samples/**/*',
                        'LICENCE' ].to_a

    # LIBRARIES
    s.require_path = 'lib'

    # Add XRCise tool as an executable
    s.bindir = 'bin'
    s.executables << 'xrcise'

    s.has_rdoc = true
  end
  Gem.manage_gems
  Gem::Builder.new(wxsugar_gemspec).build
end

Rake::PackageTask.new('wx_sugar', WXSUGAR_VERSION) do | p_task |
  p_task.need_tar_gz = true
  pkg_files = p_task.package_files
  pkg_files.include('Rakefile')
  pkg_files.include('LICENCE')
  pkg_files.include('bin/**/*')
  pkg_files.include('lib/**/*')
  pkg_files.include('samples/**/*')
end


desc 'Install the library'
task :install do
  cp_r 'lib/wx_sugar/', Config::CONFIG['sitelibdir']
end

desc 'Remove installed files'
task :uninstall do
  rm_r File.join(Config::CONFIG['sitelibdir'], 'wx_sugar')
end

