# All classes which are capable of handling events inherit from
# EvtHandler. This includes all Wx::Window subclasses and Wx::App.

class Wx::EvtHandler
  
  def self.event_class_for_type(id)
    if evt_klass = EVENT_TYPE_MAPPING[id]
      return evt_klass
    else
      warn "No event class defined for event type #{id}"
      return Wx::Event
    end
  end

  # This has maps integer EventType ids from the Wx API to Ruby
  # classes. It's called internally by the C++ code to wrap events in
  # the correct Ruby class - see EvtHandler.i and App.i
  EVENT_TYPE_MAPPING = {
    Wx::EVT_CALENDAR_SEL_CHANGED => Wx::CalendarEvent,
    Wx::EVT_CALENDAR_DAY_CHANGED => Wx::CalendarEvent,
    Wx::EVT_CALENDAR_MONTH_CHANGED => Wx::CalendarEvent,
    Wx::EVT_CALENDAR_YEAR_CHANGED => Wx::CalendarEvent,
    Wx::EVT_CALENDAR_DOUBLECLICKED => Wx::CalendarEvent,
    Wx::EVT_CALENDAR_WEEKDAY_CLICKED => Wx::CalendarEvent,
    Wx::EVT_CLOSE_WINDOW => Wx::CloseEvent,
    Wx::EVT_COMMAND_BUTTON_CLICKED => Wx::CommandEvent,
    Wx::EVT_COMMAND_CHECKBOX_CLICKED => Wx::CommandEvent,
    Wx::EVT_COMMAND_CHOICE_SELECTED => Wx::CommandEvent,
    Wx::EVT_COMMAND_LISTBOX_SELECTED => Wx::CommandEvent,
    Wx::EVT_COMMAND_LISTBOX_DOUBLECLICKED => Wx::CommandEvent,
    Wx::EVT_COMMAND_CHECKLISTBOX_TOGGLED => Wx::CommandEvent,
    Wx::EVT_COMMAND_TEXT_UPDATED => Wx::CommandEvent,
    Wx::EVT_COMMAND_TEXT_ENTER => Wx::CommandEvent,
    Wx::EVT_COMMAND_TEXT_MAXLEN => Wx::CommandEvent,
    Wx::EVT_COMMAND_MENU_SELECTED => Wx::CommandEvent,
    Wx::EVT_COMMAND_SLIDER_UPDATED => Wx::CommandEvent,
    Wx::EVT_COMMAND_RADIOBOX_SELECTED => Wx::CommandEvent,
    Wx::EVT_COMMAND_RADIOBUTTON_SELECTED => Wx::CommandEvent,
    Wx::EVT_COMMAND_SCROLLBAR_UPDATED => Wx::CommandEvent,
    Wx::EVT_COMMAND_VLBOX_SELECTED => Wx::CommandEvent,
    Wx::EVT_COMMAND_COMBOBOX_SELECTED => Wx::CommandEvent,
    Wx::EVT_COMMAND_TOOL_RCLICKED => Wx::CommandEvent,
    Wx::EVT_COMMAND_TOOL_ENTER => Wx::CommandEvent,
    Wx::EVT_COMMAND_SPINCTRL_UPDATED => Wx::CommandEvent,
    Wx::EVT_COMMAND_COMBOBOX_SELECTED => Wx::CommandEvent,
    Wx::EVT_COMMAND_TEXT_URL => Wx::TextUrlEvent,
    Wx::EVT_IDLE => Wx::IdleEvent,
    Wx::EVT_PAINT => Wx::PaintEvent,
    Wx::EVT_UPDATE_UI => Wx::UpdateUIEvent,
    Wx::EVT_SIZE => Wx::SizeEvent,
    Wx::EVT_SIZING => Wx::SizeEvent,
    Wx::EVT_MOVE => Wx::MoveEvent,
    Wx::EVT_MOVING => Wx::MoveEvent,
    Wx::EVT_TIMER => Wx::TimerEvent,
    Wx::EVT_CHAR => Wx::KeyEvent,
    Wx::EVT_CHAR_HOOK => Wx::KeyEvent,
    Wx::EVT_KEY_DOWN => Wx::KeyEvent,
    Wx::EVT_KEY_UP => Wx::KeyEvent,
    Wx::EVT_COMMAND_FIND => Wx::FindDialogEvent,
    Wx::EVT_COMMAND_FIND_NEXT => Wx::FindDialogEvent,
    Wx::EVT_COMMAND_FIND_REPLACE => Wx::FindDialogEvent,
    Wx::EVT_COMMAND_FIND_REPLACE_ALL => Wx::FindDialogEvent,
    Wx::EVT_COMMAND_FIND_CLOSE => Wx::FindDialogEvent,
    Wx::EVT_SET_FOCUS => Wx::FocusEvent,
    Wx::EVT_KILL_FOCUS => Wx::FocusEvent,
    Wx::EVT_LEFT_DOWN => Wx::MouseEvent,
    Wx::EVT_LEFT_UP => Wx::MouseEvent,
    Wx::EVT_LEFT_DCLICK => Wx::MouseEvent,
    Wx::EVT_MIDDLE_DOWN => Wx::MouseEvent,
    Wx::EVT_MIDDLE_UP => Wx::MouseEvent,
    Wx::EVT_MIDDLE_DCLICK => Wx::MouseEvent,
    Wx::EVT_RIGHT_DOWN => Wx::MouseEvent,
    Wx::EVT_RIGHT_UP => Wx::MouseEvent,
    Wx::EVT_RIGHT_DCLICK => Wx::MouseEvent,
    Wx::EVT_MOTION => Wx::MouseEvent,
    Wx::EVT_ENTER_WINDOW => Wx::MouseEvent,
    Wx::EVT_LEAVE_WINDOW => Wx::MouseEvent,
    Wx::EVT_MOUSEWHEEL => Wx::MouseEvent,
    Wx::EVT_SCROLL_THUMBTRACK => Wx::ScrollEvent,
    Wx::EVT_SCROLL_LINEUP => Wx::ScrollEvent,
    Wx::EVT_SCROLL_LINEDOWN => Wx::ScrollEvent,
    Wx::EVT_COMMAND_CHOICEBOOK_PAGE_CHANGED => Wx::ChoicebookEvent,
    Wx::EVT_COMMAND_CHOICEBOOK_PAGE_CHANGING => Wx::ChoicebookEvent,
    Wx::EVT_COMMAND_NOTEBOOK_PAGE_CHANGED => Wx::NotebookEvent,
    Wx::EVT_COMMAND_NOTEBOOK_PAGE_CHANGING => Wx::NotebookEvent,
    Wx::EVT_COMMAND_LISTBOOK_PAGE_CHANGED => Wx::ListbookEvent,
    Wx::EVT_COMMAND_LISTBOOK_PAGE_CHANGING => Wx::ListbookEvent,
    Wx::EVT_GRID_CELL_LEFT_CLICK => Wx::GridEvent,
    Wx::EVT_GRID_CELL_RIGHT_CLICK => Wx::GridEvent,
    Wx::EVT_GRID_CELL_LEFT_DCLICK => Wx::GridEvent,
    Wx::EVT_GRID_CELL_RIGHT_DCLICK => Wx::GridEvent,
    Wx::EVT_GRID_LABEL_LEFT_CLICK => Wx::GridEvent,
    Wx::EVT_GRID_LABEL_RIGHT_CLICK => Wx::GridEvent,
    Wx::EVT_GRID_LABEL_LEFT_DCLICK => Wx::GridEvent,
    Wx::EVT_GRID_LABEL_RIGHT_DCLICK => Wx::GridEvent,
    Wx::EVT_GRID_CELL_CHANGE => Wx::GridEvent,
    Wx::EVT_GRID_SELECT_CELL => Wx::GridEvent,
    Wx::EVT_GRID_EDITOR_HIDDEN => Wx::GridEvent,
    Wx::EVT_GRID_EDITOR_SHOWN => Wx::GridEvent,
    Wx::EVT_GRID_RANGE_SELECT => Wx::GridRangeSelectEvent,
    Wx::EVT_GRID_COL_SIZE => Wx::GridSizeEvent,
    Wx::EVT_GRID_ROW_SIZE => Wx::GridSizeEvent,
    Wx::EVT_GRID_EDITOR_CREATED => Wx::GridEditorCreatedEvent,
    Wx::EVT_WIZARD_PAGE_CHANGED => Wx::WizardEvent,
    Wx::EVT_WIZARD_PAGE_CHANGING => Wx::WizardEvent,
    Wx::EVT_WIZARD_CANCEL => Wx::WizardEvent,
    Wx::EVT_WIZARD_HELP => Wx::WizardEvent,
    Wx::EVT_WIZARD_FINISHED => Wx::WizardEvent,
    Wx::EVT_COMMAND_LIST_BEGIN_DRAG => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_BEGIN_RDRAG => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_BEGIN_LABEL_EDIT => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_END_LABEL_EDIT => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_DELETE_ITEM => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_DELETE_ALL_ITEMS => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_KEY_DOWN => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_INSERT_ITEM => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_COL_CLICK => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_COL_RIGHT_CLICK => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_COL_BEGIN_DRAG => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_COL_DRAGGING => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_COL_END_DRAG => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_ITEM_SELECTED => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_ITEM_DESELECTED => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_ITEM_RIGHT_CLICK => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_ITEM_MIDDLE_CLICK => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_ITEM_ACTIVATED => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_ITEM_FOCUSED => Wx::ListEvent,
    Wx::EVT_COMMAND_LIST_CACHE_HINT => Wx::ListEvent,
    Wx::EVT_COMMAND_TREE_BEGIN_DRAG => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_BEGIN_RDRAG => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_END_DRAG => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_BEGIN_LABEL_EDIT => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_END_LABEL_EDIT => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_GET_INFO => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_SET_INFO => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_ITEM_EXPANDED => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_ITEM_EXPANDING => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_ITEM_COLLAPSED => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_ITEM_COLLAPSING => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_SEL_CHANGED => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_SEL_CHANGING => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_KEY_DOWN => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_DELETE_ITEM => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_ITEM_ACTIVATED => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_ITEM_MENU => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_ITEM_RIGHT_CLICK => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_ITEM_MIDDLE_CLICK => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_STATE_IMAGE_CLICK => Wx::TreeEvent,
    Wx::EVT_COMMAND_TREE_ITEM_GETTOOLTIP => Wx::TreeEvent,
    Wx::EVT_SASH_DRAGGED => Wx::SashEvent,
    Wx::EVT_COMMAND_SPLITTER_SASH_POS_CHANGED => Wx::SplitterEvent,
    Wx::EVT_COMMAND_SPLITTER_SASH_POS_CHANGING => Wx::SplitterEvent,
    Wx::EVT_COMMAND_SPLITTER_DOUBLECLICKED => Wx::SplitterEvent,
    Wx::EVT_COMMAND_SPLITTER_UNSPLIT => Wx::SplitterEvent,
    Wx::EVT_SCROLL_TOP => Wx::ScrollEvent,
    Wx::EVT_SCROLL_BOTTOM => Wx::ScrollEvent,
    Wx::EVT_SCROLL_LINEUP => Wx::ScrollEvent,
    Wx::EVT_SCROLL_LINEDOWN => Wx::ScrollEvent,
    Wx::EVT_SCROLL_PAGEUP => Wx::ScrollEvent,
    Wx::EVT_SCROLL_PAGEDOWN => Wx::ScrollEvent,
    Wx::EVT_SCROLL_THUMBTRACK => Wx::ScrollEvent,
    Wx::EVT_SCROLL_THUMBRELEASE => Wx::ScrollEvent,
    Wx::EVT_SCROLL_CHANGED => Wx::ScrollEvent,
    Wx::EVT_SCROLLWIN_TOP => Wx::ScrollWinEvent,
    Wx::EVT_SCROLLWIN_BOTTOM => Wx::ScrollWinEvent,
    Wx::EVT_SCROLLWIN_LINEUP => Wx::ScrollWinEvent,
    Wx::EVT_SCROLLWIN_LINEDOWN => Wx::ScrollWinEvent,
    Wx::EVT_SCROLLWIN_PAGEUP => Wx::ScrollWinEvent,
    Wx::EVT_SCROLLWIN_PAGEDOWN => Wx::ScrollWinEvent,
    Wx::EVT_SCROLLWIN_THUMBTRACK => Wx::ScrollWinEvent,
    Wx::EVT_SCROLLWIN_THUMBRELEASE => Wx::ScrollWinEvent,
    Wx::EVT_ACTIVATE => Wx::ActivateEvent,
    Wx::EVT_ACTIVATE_APP => Wx::ActivateEvent,
    Wx::EVT_CREATE => Wx::WindowCreateEvent,
    Wx::EVT_DESTROY => Wx::WindowDestroyEvent,
    Wx::EVT_MENU_OPEN => Wx::MenuEvent,
    Wx::EVT_MENU_CLOSE => Wx::MenuEvent,
    Wx::EVT_MENU_HIGHLIGHT => Wx::MenuEvent,
    Wx::EVT_CONTEXT_MENU => Wx::ContextMenuEvent,
    Wx::EVT_AUI_PANE_BUTTON => Wx::AuiManagerEvent,
    Wx::EVT_AUI_PANE_CLOSE => Wx::AuiManagerEvent,
    Wx::EVT_AUI_PANE_MAXIMIZE => Wx::AuiManagerEvent,
    Wx::EVT_AUI_PANE_RESTORE => Wx::AuiManagerEvent,
    Wx::EVT_AUI_RENDER => Wx::AuiManagerEvent,
    Wx::EVT_AUI_FIND_MANAGER => Wx::AuiManagerEvent,
    Wx::EVT_COMMAND_AUINOTEBOOK_PAGE_CLOSE => Wx::AuiNotebookEvent,
    Wx::EVT_COMMAND_AUINOTEBOOK_PAGE_CHANGED => Wx::AuiNotebookEvent,
    Wx::EVT_COMMAND_AUINOTEBOOK_PAGE_CHANGING => Wx::AuiNotebookEvent,
    Wx::EVT_COMMAND_AUINOTEBOOK_BUTTON => Wx::AuiNotebookEvent,
    Wx::EVT_COMMAND_AUINOTEBOOK_BEGIN_DRAG => Wx::AuiNotebookEvent,
    Wx::EVT_COMMAND_AUINOTEBOOK_END_DRAG => Wx::AuiNotebookEvent,
    Wx::EVT_COMMAND_AUINOTEBOOK_DRAG_MOTION => Wx::AuiNotebookEvent,
    Wx::EVT_COMMAND_AUINOTEBOOK_ALLOW_DND => Wx::AuiNotebookEvent,
  }

  if defined?(Wx::Scintilla)
    EVENT_TYPE_MAPPING.merge(
      Wx::EVT_SCI_CHANGE => Wx::ScintillaEvent,
      Wx::EVT_SCI_STYLENEEDED => Wx::ScintillaEvent,
      Wx::EVT_SCI_CHARADDED => Wx::ScintillaEvent,
      Wx::EVT_SCI_SAVEPOINTREACHED => Wx::ScintillaEvent,
      Wx::EVT_SCI_SAVEPOINTLEFT => Wx::ScintillaEvent,
      Wx::EVT_SCI_ROMODIFYATTEMPT => Wx::ScintillaEvent,
      Wx::EVT_SCI_KEY => Wx::ScintillaEvent,
      Wx::EVT_SCI_DOUBLECLICK => Wx::ScintillaEvent,
      Wx::EVT_SCI_UPDATEUI => Wx::ScintillaEvent,
      Wx::EVT_SCI_MODIFIED => Wx::ScintillaEvent,
      Wx::EVT_SCI_MACRORECORD => Wx::ScintillaEvent,
      Wx::EVT_SCI_MARGINCLICK => Wx::ScintillaEvent,
      Wx::EVT_SCI_NEEDSHOWN => Wx::ScintillaEvent,
      Wx::EVT_SCI_PAINTED => Wx::ScintillaEvent,
      Wx::EVT_SCI_USERLISTSELECTION => Wx::ScintillaEvent,
      Wx::EVT_SCI_URIDROPPED => Wx::ScintillaEvent,
      Wx::EVT_SCI_DWELLSTART => Wx::ScintillaEvent,
      Wx::EVT_SCI_DWELLEND => Wx::ScintillaEvent,
      Wx::EVT_SCI_START_DRAG => Wx::ScintillaEvent,
      Wx::EVT_SCI_DRAG_OVER => Wx::ScintillaEvent,
      Wx::EVT_SCI_DO_DROP => Wx::ScintillaEvent,
      Wx::EVT_SCI_ZOOM => Wx::ScintillaEvent,
      Wx::EVT_SCI_HOTSPOT_CLICK => Wx::ScintillaEvent,
      Wx::EVT_SCI_HOTSPOT_DCLICK => Wx::ScintillaEvent,
      Wx::EVT_SCI_CALLTIP_CLICK => Wx::ScintillaEvent )
  end
end

