/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.22
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxBitmapButton_WRAP_H_
#define SWIG_WxBitmapButton_WRAP_H_

class Swig::Director;


class SwigDirector_wxBitmapButton : public wxBitmapButton, public Swig::Director {

public:
    SwigDirector_wxBitmapButton(VALUE self, bool disown = false);
    SwigDirector_wxBitmapButton(VALUE self, wxWindow *parent, wxWindowID id, wxBitmap const &bitmap, wxPoint const &pos = wxDefaultPosition, wxSize const &size = wxDefaultSize, long style = wxBU_AUTODRAW, wxValidator const &validator = wxDefaultValidator, wxString const &name = "button", bool disown = false);
};


#endif
