/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.21
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxBitmap_WRAP_H_
#define SWIG_WxBitmap_WRAP_H_

class Swig::Director;


class SwigDirector_wxBitmap : public wxBitmap, public Swig::Director {

public:
    SwigDirector_wxBitmap(VALUE self, bool disown = 0);
    SwigDirector_wxBitmap(VALUE self, wxBitmap const &bitmap, bool disown = 0);
    SwigDirector_wxBitmap(VALUE self, int width, int height, int depth = -1, bool disown = 0);
    SwigDirector_wxBitmap(VALUE self, char const **bits, bool disown = 0);
    SwigDirector_wxBitmap(VALUE self, wxString const &name, wxBitmapType type, bool disown = 0);
    SwigDirector_wxBitmap(VALUE self, wxImage const &img, int depth = -1, bool disown = 0);
    virtual bool Create(int width, int height, int depth = -1);
};


#endif
