/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.22
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxCheckBox_WRAP_H_
#define SWIG_WxCheckBox_WRAP_H_

class Swig::Director;


class SwigDirector_wxCheckBox : public wxCheckBox, public Swig::Director {

public:
    SwigDirector_wxCheckBox(VALUE self, bool disown = false);
    SwigDirector_wxCheckBox(VALUE self, wxWindow *parent, wxWindowID id, wxString const &label, wxPoint const &pos = wxDefaultPosition, wxSize const &size = wxDefaultSize, long style = 0, wxValidator const &val = wxDefaultValidator, wxString const &name = "checkBox", bool disown = false);
};


#endif
