/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxDirDialog_WRAP_H_
#define SWIG_WxDirDialog_WRAP_H_

class Swig::Director;


class SwigDirector_wxDirDialog : public wxDirDialog, public Swig::Director {

public:
    SwigDirector_wxDirDialog(VALUE self, wxWindow *parent, wxString const &message = wxT("Choose"), wxString const &defaultPath = wxT(""), long style = 0, wxPoint const &pos = wxDefaultPosition, wxSize const &size = wxDefaultSize, wxString const &name = wxT("wxDirCtrl"));
    virtual ~SwigDirector_wxDirDialog();
};


#endif
