/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.22
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxFont_WRAP_H_
#define SWIG_WxFont_WRAP_H_

class Swig::Director;


class SwigDirector_wxFont : public wxFont, public Swig::Director {

public:
    SwigDirector_wxFont(VALUE self, bool disown = false);
    SwigDirector_wxFont(VALUE self, int pointSize, int family, int style, int weight, bool const underline = false, wxString const &faceName = "", wxFontEncoding encoding = wxFONTENCODING_DEFAULT, bool disown = false);
};


#endif
