/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.21
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIG_NOINCLUDE
#define SWIG_DIRECTORS

#ifdef __cplusplus
template<class T> class SwigValueWrapper {
    T *tt;
public:
    SwigValueWrapper() : tt(0) { }
    SwigValueWrapper(const SwigValueWrapper<T>& rhs) : tt(new T(*rhs.tt)) { }
    SwigValueWrapper(const T& t) : tt(new T(t)) { }
    ~SwigValueWrapper() { delete tt; } 
    SwigValueWrapper& operator=(const T& t) { delete tt; tt = new T(t); return *this; }
    operator T&() const { return *tt; }
    T *operator&() { return tt; }
private:
    SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
};                                                    
#endif

/* ruby.swg */
/* Implementation : RUBY */
#define SWIGRUBY 1

#include "ruby.h"

/* Flags for pointer conversion */
#define SWIG_POINTER_EXCEPTION     0x1
#define SWIG_POINTER_DISOWN        0x2

#define NUM2USHRT(n) (\
    (0 <= NUM2UINT(n) && NUM2UINT(n) <= USHRT_MAX)\
    ? (unsigned short) NUM2UINT(n) \
    : (rb_raise(rb_eArgError, "integer %d out of range of `unsigned short'",\
               NUM2UINT(n)), (short)0)\
)

#define NUM2SHRT(n) (\
    (SHRT_MIN <= NUM2INT(n) && NUM2INT(n) <= SHRT_MAX)\
    ? (short)NUM2INT(n)\
    : (rb_raise(rb_eArgError, "integer %d out of range of `short'",\
               NUM2INT(n)), (short)0)\
)

/* Ruby 1.7 defines NUM2LL(), LL2NUM() and ULL2NUM() macros */
#ifndef NUM2LL
#define NUM2LL(x) NUM2LONG((x))
#endif
#ifndef LL2NUM
#define LL2NUM(x) INT2NUM((long) (x))
#endif
#ifndef ULL2NUM
#define ULL2NUM(x) UINT2NUM((unsigned long) (x))
#endif

/* Ruby 1.7 doesn't (yet) define NUM2ULL() */
#ifndef NUM2ULL
#ifdef HAVE_LONG_LONG
#define NUM2ULL(x) rb_num2ull((x))
#else
#define NUM2ULL(x) NUM2ULONG(x)
#endif
#endif

/*
 * Need to be very careful about how these macros are defined, especially
 * when compiling C++ code or C code with an ANSI C compiler.
 *
 * VALUEFUNC(f) is a macro used to typecast a C function that implements
 * a Ruby method so that it can be passed as an argument to API functions
 * like rb_define_method() and rb_define_singleton_method().
 *
 * VOIDFUNC(f) is a macro used to typecast a C function that implements
 * either the "mark" or "free" stuff for a Ruby Data object, so that it
 * can be passed as an argument to API functions like Data_Wrap_Struct()
 * and Data_Make_Struct().
 */
 
#ifdef __cplusplus
#  ifndef RUBY_METHOD_FUNC /* These definitions should work for Ruby 1.4.6 */
#    define VALUEFUNC(f) ((VALUE (*)()) f)
#    define VOIDFUNC(f)  ((void (*)()) f)
#  else
#    ifndef ANYARGS /* These definitions should work for Ruby 1.6 */
#      define VALUEFUNC(f) ((VALUE (*)()) f)
#      define VOIDFUNC(f)  ((RUBY_DATA_FUNC) f)
#    else /* These definitions should work for Ruby 1.7 */
#      define VALUEFUNC(f) ((VALUE (*)(ANYARGS)) f)
#      define VOIDFUNC(f)  ((RUBY_DATA_FUNC) f)
#    endif
#  endif
#else
#  define VALUEFUNC(f) (f)
#  define VOIDFUNC(f) (f)
#endif

typedef struct {
  VALUE klass;
  VALUE mImpl;
  void  (*mark)(void *);
  void  (*destroy)(void *);
} swig_class;

/* Don't use for expressions have side effect */
#ifndef RB_STRING_VALUE
#define RB_STRING_VALUE(s) (TYPE(s) == T_STRING ? (s) : (*(volatile VALUE *)&(s) = rb_str_to_str(s)))
#endif
#ifndef StringValue
#define StringValue(s) RB_STRING_VALUE(s)
#endif
#ifndef StringValuePtr
#define StringValuePtr(s) RSTRING(RB_STRING_VALUE(s))->ptr
#endif
#ifndef StringValueLen
#define StringValueLen(s) RSTRING(RB_STRING_VALUE(s))->len
#endif
#ifndef SafeStringValue
#define SafeStringValue(v) do {\
    StringValue(v);\
    rb_check_safe_str(v);\
} while (0)
#endif

#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
#define rb_define_alloc_func(klass, func) rb_define_singleton_method((klass), "new", VALUEFUNC((func)), -1)
#define rb_undef_alloc_func(klass) rb_undef_method(CLASS_OF((klass)), "new")
#endif

/* Contract support */

#define SWIG_contract_assert(expr, msg) if (!(expr)) { rb_raise(rb_eRuntimeError, (char *) msg ); } else


/*************************************************************** -*- c -*-
 * ruby/precommon.swg
 *
 * Rename all exported symbols from common.swg, to avoid symbol
 * clashes if multiple interpreters are included
 *
 ************************************************************************/

#define SWIG_TypeRegister    SWIG_Ruby_TypeRegister
#define SWIG_TypeCheck       SWIG_Ruby_TypeCheck
#define SWIG_TypeCast        SWIG_Ruby_TypeCast
#define SWIG_TypeDynamicCast SWIG_Ruby_TypeDynamicCast
#define SWIG_TypeName        SWIG_Ruby_TypeName
#define SWIG_TypeQuery       SWIG_Ruby_TypeQuery
#define SWIG_TypeClientData  SWIG_Ruby_TypeClientData
#define SWIG_PackData        SWIG_Ruby_PackData 
#define SWIG_UnpackData      SWIG_Ruby_UnpackData 

/* Also rename all exported symbols from rubydef.swig */

/* Common SWIG API */
#define SWIG_ConvertPtr(obj, pp, type, flags) \
  SWIG_Ruby_ConvertPtr(obj, pp, type, flags)
#define SWIG_NewPointerObj(p, type, flags) \
  SWIG_Ruby_NewPointerObj(p, type, flags)
#define SWIG_MustGetPtr(p, type, argnum, flags) \
  SWIG_Ruby_MustGetPtr(p, type, argnum, flags)

/* Ruby-specific SWIG API */

#define SWIG_InitRuntime() \
  SWIG_Ruby_InitRuntime()
#define SWIG_define_class(ty) \
  SWIG_Ruby_define_class(ty)
#define SWIG_NewClassInstance(value, ty) \
  SWIG_Ruby_NewClassInstance(value, ty)
#define SWIG_MangleStr(value) \
  SWIG_Ruby_MangleStr(value)
#define SWIG_CheckConvert(value, ty) \
  SWIG_Ruby_CheckConvert(value, ty)
#define SWIG_NewPackedObj(ptr, sz, ty) \
  SWIG_Ruby_NewPackedObj(ptr, sz, ty)
#define SWIG_ConvertPacked(obj, ptr, sz, ty, flags) \
  SWIG_Ruby_ConvertPacked(obj, ptr, sz, ty, flags)


/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#  if defined(_MSC_VER) || defined(__GNUC__)
#    if defined(STATIC_LINKED)
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) extern a
#    else
#      define SWIGEXPORT(a) __declspec(dllexport) a
#      define SWIGIMPORT(a) extern a
#    endif
#  else
#    if defined(__BORLANDC__)
#      define SWIGEXPORT(a) a _export
#      define SWIGIMPORT(a) a _export
#    else
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) a
#    endif
#  endif
#else
#  define SWIGEXPORT(a) a
#  define SWIGIMPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#  define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#  define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGIMPORT(void *)           SWIG_TypeCast(swig_type_info *, void *);
SWIGIMPORT(swig_type_info *) SWIG_TypeDynamicCast(swig_type_info *, void **);
SWIGIMPORT(const char *)     SWIG_TypeName(const swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGIMPORT(void)             SWIG_TypeClientData(swig_type_info *, void *);
SWIGIMPORT(char *)           SWIG_PackData(char *, void *, int);
SWIGIMPORT(char *)           SWIG_UnpackData(char *, void *, int);

#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti) {
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      if (tc->clientdata) ti->clientdata = tc->clientdata;
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
  l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) {
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/* Return the name associated with this type */
SWIGRUNTIME(const char *)
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata == clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0))
          SWIG_TypeClientData(tc,clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu = 0;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

#endif

#ifdef __cplusplus
}
#endif

/* rubydec.swg -*- c -*- */
#ifdef __cplusplus
extern "C" {
#endif

SWIGIMPORT(void)   SWIG_Ruby_InitRuntime(void);
SWIGIMPORT(void)   SWIG_Ruby_define_class(swig_type_info *);
SWIGIMPORT(VALUE)  SWIG_Ruby_NewPointerObj(void *, swig_type_info *, int);
SWIGIMPORT(VALUE)  SWIG_Ruby_NewClassInstance(VALUE, swig_type_info *);
SWIGIMPORT(char *) SWIG_Ruby_MangleStr(VALUE);
SWIGIMPORT(int)    SWIG_Ruby_ConvertPtr(VALUE, void**, swig_type_info *, int);
SWIGIMPORT(void *) SWIG_Ruby_MustGetPtr(VALUE, swig_type_info *, int, int);
SWIGIMPORT(int)    SWIG_Ruby_CheckConvert(VALUE, swig_type_info *);
SWIGIMPORT(VALUE)  SWIG_Ruby_NewPackedObj(void *ptr, int sz, swig_type_info *type);
SWIGIMPORT(void)   SWIG_Ruby_ConvertPacked(VALUE obj, void *ptr, int sz, swig_type_info *ty, int flags);

#ifdef __cplusplus
}
#endif


/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_wxIcon swig_types[0] 
#define  SWIGTYPE_p_wxSize swig_types[1] 
#define  SWIGTYPE_p_wxWindow swig_types[2] 
#define  SWIGTYPE_p_wxString swig_types[3] 
#define  SWIGTYPE_p_wxStatusBar swig_types[4] 
#define  SWIGTYPE_p_wxFrame swig_types[5] 
#define  SWIGTYPE_p_wxMenuBar swig_types[6] 
#define  SWIGTYPE_p_wxRegion swig_types[7] 
#define  SWIGTYPE_p_int swig_types[8] 
#define  SWIGTYPE_p_wxToolBar swig_types[9] 
#define  SWIGTYPE_p_wxPoint swig_types[10] 
#define  SWIGTYPE_p_wxIconBundle swig_types[11] 
static swig_type_info *swig_types[13];

/* -------- TYPES TABLE (END) -------- */

#define SWIG_init    Init_wxFrame
#define SWIG_name    "WxFrame"

static VALUE alive = Qnil;

static VALUE mWxFrame;
   extern VALUE mWx;

#  undef GetClassName
#  undef GetClassInfo
#  undef Yield
#  undef GetMessage
#  undef FindWindow
#  undef GetCharWidth
#  undef DrawText
#  undef StartDoc
#  undef CreateDialog
#  undef Sleep
#  undef _
#  undef Connect
#  undef connect

#include <wx/wx.h>

void GcMarkDeleted(void *);
bool GcIsDeleted(void *);


#include <wx/datetime.h>


class wxRbCallback : public wxObject 
{
    DECLARE_ABSTRACT_CLASS(wxRbCallback);
public:
    wxRbCallback(VALUE func) { m_func = func; }
    wxRbCallback(const wxRbCallback &other) { m_func = other.m_func; }
 
    void GenericEventThunker(wxEvent &event)
    {
        extern swig_class cWxEvent;
        EventThunker(event, cWxEvent.klass);
    }
    
    void CalendarEventThunker(wxEvent &event)
    {
        extern swig_class cWxCalendarEvent;
        EventThunker(event, cWxCalendarEvent.klass);
    }
    
    void CloseEventThunker(wxEvent &event)
    {
        extern swig_class cWxCloseEvent;
        EventThunker(event, cWxCloseEvent.klass);
    }
    
    void CommandEventThunker(wxEvent &event)
    {
        extern swig_class cWxCommandEvent;
        EventThunker(event, cWxCommandEvent.klass);
    }
    
    void PaintEventThunker(wxEvent &event)
    {
        extern swig_class cWxPaintEvent;
        EventThunker(event, cWxPaintEvent.klass);
    }
    
    void UpdateUIEventThunker(wxEvent &event)
    {
        extern swig_class cWxUpdateUIEvent;
        EventThunker(event, cWxUpdateUIEvent.klass);
    }
    
    void EventThunker(wxEvent &event, VALUE cEvent)
    {
        static VALUE vevent;
        vevent = Data_Wrap_Struct(cEvent, 0, 0, 0);
        DATA_PTR(vevent) = &event;
        
        wxRbCallback *cb = (wxRbCallback *)event.m_callbackUserData;
        rb_funcall(cb->m_func, rb_intern("call"),1,vevent);
    }
                                                                                
    VALUE       m_func;
};


extern swig_class cWxWindow;
swig_class cWxFrame;
static void free_wxFrame(wxFrame *);
/***********************************************************************
 * director.swg
 *
 * This file contains support for director classes that proxy
 * method calls from C++ to Ruby extensions.
 *
 * Author : Lyle Johnson (lyle@users.sourceforge.net)
 *          Based on the original Python implementation by
 *          Mark Rose (mrose@stm.lbl.gov).
 ************************************************************************/

#ifdef __cplusplus

#include <string>

namespace Swig {
  struct body_args {
    VALUE recv;
    ID id;
    int argc;
    VALUE *argv;
  };

  /* Base class for director exceptions */
  class DirectorException {
    protected:
      VALUE swig_error;
    protected:
      DirectorException(VALUE error=Qnil) : swig_error(error) {}
    public:
      VALUE getType() const  { 
        return CLASS_OF(swig_error); 
      }
      VALUE getError() const {
        return swig_error;
      }
      virtual ~DirectorException() {}
  };

  /* Type mismatch in the return value from a Ruby method call */
  class DirectorTypeMismatchException : public Swig::DirectorException {
    public:
      DirectorTypeMismatchException(const char *msg="") {
        VALUE str = rb_str_new2("Swig director type mismatch: ");
        rb_str_concat(str, rb_str_new2(msg));
        swig_error = rb_exc_new3(rb_eTypeError, str);
      }
  };

  /* Any Ruby exception that occurs during a director method call */
  class DirectorMethodException : public Swig::DirectorException {
    public:
      DirectorMethodException(VALUE error) : Swig::DirectorException(error) {}
  };

  /* Attempted to call a pure virtual method via a director method */
  class DirectorPureVirtualException : public Swig::DirectorException {};


  /* Simple thread abstraction for pthreads on win32 */
#ifdef __THREAD__
#define __PTHREAD__
#if defined(_WIN32) || defined(__WIN32__)
#define pthread_mutex_lock EnterCriticalSection
#define pthread_mutex_unlock LeaveCriticalSection
#define pthread_mutex_t CRITICAL_SECTION
#define MUTEX_INIT(var) CRITICAL_SECTION var
#else
#include <pthread.h>
#define MUTEX_INIT(var) pthread_mutex_t var = PTHREAD_MUTEX_INITIALIZER 
#endif
#endif

  /* director base class */
  class Director {
    private:
      /* pointer to the wrapped Ruby object */
      VALUE swig_self;
      /* flag indicating whether the object is owned by Ruby or c++ */
      mutable bool swig_disown_flag;
      /* shared flag for breaking recursive director calls */
      static bool swig_up;

#ifdef __PTHREAD__
      /* locks for sharing the swig_up flag in a threaded environment */
      static pthread_mutex_t swig_mutex_up;
      static bool swig_mutex_active;
      static pthread_t swig_mutex_thread;
#endif

      /* reset the swig_up flag once the routing direction has been determined */
#ifdef __PTHREAD__
      void swig_clear_up() const { 
        Swig::Director::swig_up = false; 
        Swig::Director::swig_mutex_active = false;
        pthread_mutex_unlock(&swig_mutex_up);
      }
#else
      void swig_clear_up() const { 
        Swig::Director::swig_up = false; 
      }
#endif

    public:
      /* wrap a Ruby object, optionally taking ownership */
      Director(VALUE self, bool disown) : swig_self(self), swig_disown_flag(disown) {

    printf("Frame.cpp" " new Director %p\n", this);
    if(alive == Qnil)
    {
        rb_global_variable(&alive);
        alive = rb_hash_new();
    }
    rb_hash_aset(alive, INT2NUM((int)this), self);
      }

      /* discard our reference at destruction */
      virtual ~Director() {

    printf("Frame.cpp" " ~Director %p\n", this);
    GcMarkDeleted(this);
      }

      /* return a pointer to the wrapped Ruby object */
      VALUE swig_get_self() const { 
        return swig_self; 
      }

      /* get the swig_up flag to determine if the method call should be routed
       * to the c++ base class or through the wrapped Ruby object
       */
#ifdef __PTHREAD__
      bool swig_get_up() const { 
        if (Swig::Director::swig_mutex_active) {
          if (pthread_equal(Swig::Director::swig_mutex_thread, pthread_self())) {
            bool up = swig_up;
            swig_clear_up();
            return up;
          }
        }
        return false;
      }
#else 
      bool swig_get_up() const { 
        bool up = swig_up;
        swig_up = false;
        return up;
      }
#endif

      /* set the swig_up flag if the next method call should be directed to
       * the c++ base class rather than the wrapped Ruby object
       */
#ifdef __PTHREAD__
      void swig_set_up() const { 
        pthread_mutex_lock(&Swig::Director::swig_mutex_up);
        Swig::Director::swig_mutex_thread = pthread_self();
        Swig::Director::swig_mutex_active = true;
        Swig::Director::swig_up = true;
      }
#else 
      void swig_set_up() const { 
        Swig::Director::swig_up = true; 
      }
#endif

      /* acquire ownership of the wrapped Ruby object (the sense of "disown"
       * is from Ruby) */
      void swig_disown() const { 
        if (!swig_disown_flag) { 
          swig_disown_flag = true;
        } 
      }
  };

//  bool Swig::Director::swig_up = false;

#ifdef __PTHREAD__
  MUTEX_INIT(Swig::Director::swig_mutex_up);
  pthread_t Swig::Director::swig_mutex_thread;
  bool Swig::Director::swig_mutex_active = false;
#endif

}

#endif /* __cplusplus */




/* ---------------------------------------------------
 * C++ director class methods
 * --------------------------------------------------- */

#include "Frame.h"

SwigDirector_wxFrame::SwigDirector_wxFrame(VALUE self, bool disown): wxFrame(), Swig::Director(self, disown) {
    
}



SwigDirector_wxFrame::SwigDirector_wxFrame(VALUE self, wxWindow *parent, wxWindowID id, wxString const &title, wxPoint const &pos, wxSize const &size, long style, wxString const &name, bool disown): wxFrame(parent, id, title, pos, size, style, name), Swig::Director(self, disown) {
    
}



void SwigDirector_wxFrame::SetStatusWidths(int n, int *widths) {
    VALUE obj0 = Qnil ;
    VALUE obj1 = Qnil ;
    VALUE result;
    
    if (swig_get_up()) {
        wxFrame::SetStatusWidths(n,widths);
        return;
    }
    obj0 = INT2NUM(n);
    obj1 = SWIG_NewPointerObj(widths, SWIGTYPE_p_int, 0);
    result = rb_funcall(swig_get_self(), rb_intern("set_status_widths"), 2,obj0,obj1);
}


wxToolBar *SwigDirector_wxFrame::CreateToolBar(long style, wxWindowID id, wxString const &name) {
    VALUE obj0 = Qnil ;
    VALUE obj1 = Qnil ;
    VALUE obj2 = Qnil ;
    wxToolBar *c_result ;
    VALUE result;
    
    if (swig_get_up()) {
        return wxFrame::CreateToolBar(style,id,name);
    }
    obj0 = LONG2NUM(style);
    obj1 = INT2NUM(id);
    obj2 = rb_str_new2((&name)->c_str());
    result = rb_funcall(swig_get_self(), rb_intern("create_tool_bar"), 3,obj0,obj1,obj2);
    if ((SWIG_ConvertPtr(result,(void **) &c_result, SWIGTYPE_p_wxToolBar,SWIG_POINTER_EXCEPTION | 0 )) == -1) throw Swig::DirectorTypeMismatchException("Pointer conversion failed.");
    return c_result;
}


wxStatusBar *SwigDirector_wxFrame::OnCreateStatusBar(int number, long style, wxWindowID id, wxString const &name) {
    VALUE obj0 = Qnil ;
    VALUE obj1 = Qnil ;
    VALUE obj2 = Qnil ;
    VALUE obj3 = Qnil ;
    wxStatusBar *c_result ;
    VALUE result;
    
    if (swig_get_up()) {
        return wxFrame::OnCreateStatusBar(number,style,id,name);
    }
    obj0 = INT2NUM(number);
    obj1 = LONG2NUM(style);
    obj2 = INT2NUM(id);
    obj3 = rb_str_new2((&name)->c_str());
    result = rb_funcall(swig_get_self(), rb_intern("on_create_status_bar"), 4,obj0,obj1,obj2,obj3);
    if ((SWIG_ConvertPtr(result,(void **) &c_result, SWIGTYPE_p_wxStatusBar,SWIG_POINTER_EXCEPTION | 0 )) == -1) throw Swig::DirectorTypeMismatchException("Pointer conversion failed.");
    return c_result;
}


wxStatusBar *SwigDirector_wxFrame::CreateStatusBar(int number, long style, wxWindowID id, wxString const &name) {
    VALUE obj0 = Qnil ;
    VALUE obj1 = Qnil ;
    VALUE obj2 = Qnil ;
    VALUE obj3 = Qnil ;
    wxStatusBar *c_result ;
    VALUE result;
    
    if (swig_get_up()) {
        return wxFrame::CreateStatusBar(number,style,id,name);
    }
    obj0 = INT2NUM(number);
    obj1 = LONG2NUM(style);
    obj2 = INT2NUM(id);
    obj3 = rb_str_new2((&name)->c_str());
    result = rb_funcall(swig_get_self(), rb_intern("create_status_bar"), 4,obj0,obj1,obj2,obj3);
    if ((SWIG_ConvertPtr(result,(void **) &c_result, SWIGTYPE_p_wxStatusBar,SWIG_POINTER_EXCEPTION | 0 )) == -1) throw Swig::DirectorTypeMismatchException("Pointer conversion failed.");
    return c_result;
}


void SwigDirector_wxFrame::SetStatusText(wxString const &text, int number) {
    VALUE obj0 = Qnil ;
    VALUE obj1 = Qnil ;
    VALUE result;
    
    if (swig_get_up()) {
        wxFrame::SetStatusText(text,number);
        return;
    }
    obj0 = rb_str_new2((&text)->c_str());
    obj1 = INT2NUM(number);
    result = rb_funcall(swig_get_self(), rb_intern("set_status_text"), 2,obj0,obj1);
}


wxToolBar *SwigDirector_wxFrame::OnCreateToolBar(long style, wxWindowID id, wxString const &name) {
    VALUE obj0 = Qnil ;
    VALUE obj1 = Qnil ;
    VALUE obj2 = Qnil ;
    wxToolBar *c_result ;
    VALUE result;
    
    if (swig_get_up()) {
        return wxFrame::OnCreateToolBar(style,id,name);
    }
    obj0 = LONG2NUM(style);
    obj1 = INT2NUM(id);
    obj2 = rb_str_new2((&name)->c_str());
    result = rb_funcall(swig_get_self(), rb_intern("on_create_tool_bar"), 3,obj0,obj1,obj2);
    if ((SWIG_ConvertPtr(result,(void **) &c_result, SWIGTYPE_p_wxToolBar,SWIG_POINTER_EXCEPTION | 0 )) == -1) throw Swig::DirectorTypeMismatchException("Pointer conversion failed.");
    return c_result;
}


void SwigDirector_wxFrame::SetTitle(wxString const &title) {
    VALUE obj0 = Qnil ;
    VALUE result;
    
    if (swig_get_up()) {
        wxFrame::SetTitle(title);
        return;
    }
    obj0 = rb_str_new2((&title)->c_str());
    result = rb_funcall(swig_get_self(), rb_intern("set_title"), 1,obj0);
}


#ifdef HAVE_RB_DEFINE_ALLOC_FUNC
static VALUE
_wrap_wxFrame_allocate(VALUE self) {
#else
    static VALUE
    _wrap_wxFrame_allocate(int argc, VALUE *argv, VALUE self) {
#endif
        
        
        VALUE vresult = SWIG_NewClassInstance(self, SWIGTYPE_p_wxFrame);
#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
        rb_obj_call_init(vresult, argc, argv);
#endif
        return vresult;
    }
    

static VALUE
_wrap_new_wxFrame(int argc, VALUE *argv, VALUE self) {
    VALUE arg1 ;
    wxWindow *arg2 = (wxWindow *) 0 ;
    wxWindowID arg3 ;
    wxString *arg4 = 0 ;
    wxPoint const &arg5_defvalue = wxDefaultPosition ;
    wxPoint *arg5 = (wxPoint *) &arg5_defvalue ;
    wxSize const &arg6_defvalue = wxDefaultSize ;
    wxSize *arg6 = (wxSize *) &arg6_defvalue ;
    long arg7 = (long) wxDEFAULT_FRAME_STYLE ;
    wxString const &arg8_defvalue = "frame" ;
    wxString *arg8 = (wxString *) &arg8_defvalue ;
    wxFrame *result;
    
    if ((argc < 3) || (argc > 7))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 3)",argc);
    arg1 = self;
    SWIG_ConvertPtr(argv[0], (void **) &arg2, SWIGTYPE_p_wxWindow, 1);
    arg3 = NUM2INT(argv[1]);
    {
        arg4 = new wxString(STR2CSTR(argv[2]));
    }
    if (argc > 3) {
        SWIG_ConvertPtr(argv[3], (void **) &arg5, SWIGTYPE_p_wxPoint, 1); if (arg5 == NULL) rb_raise(rb_eTypeError, "null reference");
    }
    if (argc > 4) {
        SWIG_ConvertPtr(argv[4], (void **) &arg6, SWIGTYPE_p_wxSize, 1); if (arg6 == NULL) rb_raise(rb_eTypeError, "null reference");
    }
    if (argc > 5) {
        arg7 = NUM2LONG(argv[5]);
    }
    if (argc > 6) {
        {
            arg8 = new wxString(STR2CSTR(argv[6]));
        }
    }
    if ( CLASS_OF(self) != Qnil ) {
        /* subclassed */
        result = (wxFrame *)new SwigDirector_wxFrame(arg1,arg2,arg3,(wxString const &)*arg4,(wxPoint const &)*arg5,(wxSize const &)*arg6,arg7,(wxString const &)*arg8,0);
        
    } else {
        result = (wxFrame *)new wxFrame(arg2,arg3,(wxString const &)*arg4,(wxPoint const &)*arg5,(wxSize const &)*arg6,arg7,(wxString const &)*arg8);
        
    }
    DATA_PTR(self) = result;
    return self;
}


static void
free_wxFrame(wxFrame *arg1) {
    Swig::Director* director = (Swig::Director*)(SwigDirector_wxFrame*)arg1;
    printf("Frame.cpp" " Checking %p\n", director);
    if (GcIsDeleted(director))
    {
        printf("%p is already dead!\n", director);
        return;
    }
    printf("deleting %p\n", director);
    delete arg1;
}
static VALUE
_wrap_wxFrame_Centre(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    int arg2 = (int) wxBOTH ;
    
    if ((argc < 0) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    if (argc > 0) {
        arg2 = NUM2INT(argv[0]);
    }
    (arg1)->Centre(arg2);
    
    return Qnil;
}


static VALUE
_wrap_wxFrame_Command(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    arg2 = NUM2INT(argv[0]);
    (arg1)->Command(arg2);
    
    return Qnil;
}


static VALUE
_wrap_wxFrame_Create(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    wxWindow *arg2 = (wxWindow *) 0 ;
    wxWindowID arg3 ;
    wxString *arg4 = 0 ;
    wxPoint const &arg5_defvalue = wxDefaultPosition ;
    wxPoint *arg5 = (wxPoint *) &arg5_defvalue ;
    wxSize const &arg6_defvalue = wxDefaultSize ;
    wxSize *arg6 = (wxSize *) &arg6_defvalue ;
    long arg7 = (long) wxDEFAULT_FRAME_STYLE ;
    wxString const &arg8_defvalue = "frame" ;
    wxString *arg8 = (wxString *) &arg8_defvalue ;
    bool result;
    VALUE vresult = Qnil;
    
    if ((argc < 3) || (argc > 7))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 3)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    SWIG_ConvertPtr(argv[0], (void **) &arg2, SWIGTYPE_p_wxWindow, 1);
    arg3 = NUM2INT(argv[1]);
    {
        arg4 = new wxString(STR2CSTR(argv[2]));
    }
    if (argc > 3) {
        SWIG_ConvertPtr(argv[3], (void **) &arg5, SWIGTYPE_p_wxPoint, 1); if (arg5 == NULL) rb_raise(rb_eTypeError, "null reference");
    }
    if (argc > 4) {
        SWIG_ConvertPtr(argv[4], (void **) &arg6, SWIGTYPE_p_wxSize, 1); if (arg6 == NULL) rb_raise(rb_eTypeError, "null reference");
    }
    if (argc > 5) {
        arg7 = NUM2LONG(argv[5]);
    }
    if (argc > 6) {
        {
            arg8 = new wxString(STR2CSTR(argv[6]));
        }
    }
    result = (bool)(arg1)->Create(arg2,arg3,(wxString const &)*arg4,(wxPoint const &)*arg5,(wxSize const &)*arg6,arg7,(wxString const &)*arg8);
    
    vresult = result ? Qtrue : Qfalse;
    return vresult;
}


static VALUE
_wrap_wxFrame_CreateStatusBar(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    int arg2 = (int) 1 ;
    long arg3 = (long) 0 ;
    wxWindowID arg4 = (wxWindowID) -1 ;
    wxString const &arg5_defvalue = "statusBar" ;
    wxString *arg5 = (wxString *) &arg5_defvalue ;
    wxStatusBar *result;
    Swig::Director *director = 0;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 4))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    if (argc > 0) {
        arg2 = NUM2INT(argv[0]);
    }
    if (argc > 1) {
        arg3 = NUM2LONG(argv[1]);
    }
    if (argc > 2) {
        arg4 = NUM2INT(argv[2]);
    }
    if (argc > 3) {
        {
            arg5 = new wxString(STR2CSTR(argv[3]));
        }
    }
    director = dynamic_cast<Swig::Director *>(arg1);
    if (director && (director->swig_get_self() == self)) director->swig_set_up();
    result = (wxStatusBar *)(arg1)->CreateStatusBar(arg2,arg3,arg4,(wxString const &)*arg5);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_wxStatusBar,0);
    return vresult;
}


static VALUE
_wrap_wxFrame_CreateToolBar(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    long arg2 = (long) wxNO_BORDER ;
    wxWindowID arg3 = (wxWindowID) -1 ;
    wxString const &arg4_defvalue = "toolBar" ;
    wxString *arg4 = (wxString *) &arg4_defvalue ;
    wxToolBar *result;
    Swig::Director *director = 0;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 3))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    if (argc > 0) {
        arg2 = NUM2LONG(argv[0]);
    }
    if (argc > 1) {
        arg3 = NUM2INT(argv[1]);
    }
    if (argc > 2) {
        {
            arg4 = new wxString(STR2CSTR(argv[2]));
        }
    }
    director = dynamic_cast<Swig::Director *>(arg1);
    if (director && (director->swig_get_self() == self)) director->swig_set_up();
    result = (wxToolBar *)(arg1)->CreateToolBar(arg2,arg3,(wxString const &)*arg4);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_wxToolBar,0);
    return vresult;
}


static VALUE
_wrap_wxFrame_GetClientAreaOrigin(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    wxPoint result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    result = ((wxFrame const *)arg1)->GetClientAreaOrigin();
    
    {
        wxPoint * resultptr;
        resultptr = new wxPoint((wxPoint &)result);
        vresult = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_wxPoint, 1);
    }
    return vresult;
}


static VALUE
_wrap_wxFrame_GetMenuBar(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    wxMenuBar *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    result = (wxMenuBar *)((wxFrame const *)arg1)->GetMenuBar();
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_wxMenuBar,0);
    return vresult;
}


static VALUE
_wrap_wxFrame_GetStatusBar(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    wxStatusBar *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    result = (wxStatusBar *)((wxFrame const *)arg1)->GetStatusBar();
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_wxStatusBar,0);
    return vresult;
}


static VALUE
_wrap_wxFrame_GetStatusBarPane(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    result = (int)(arg1)->GetStatusBarPane();
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_wxFrame_GetTitle(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    wxString result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    result = ((wxFrame const *)arg1)->GetTitle();
    
    {
        vresult = rb_str_new2((&result)->c_str());
    }
    return vresult;
}


static VALUE
_wrap_wxFrame_GetToolBar(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    wxToolBar *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    result = (wxToolBar *)((wxFrame const *)arg1)->GetToolBar();
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_wxToolBar,0);
    return vresult;
}


static VALUE
_wrap_wxFrame_Iconize(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    bool arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    arg2 = RTEST(argv[0]);
    (arg1)->Iconize(arg2);
    
    return Qnil;
}


static VALUE
_wrap_wxFrame_IsFullScreen(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    bool result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    result = (bool)(arg1)->IsFullScreen();
    
    vresult = result ? Qtrue : Qfalse;
    return vresult;
}


static VALUE
_wrap_wxFrame_IsIconized(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    bool result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    result = (bool)((wxFrame const *)arg1)->IsIconized();
    
    vresult = result ? Qtrue : Qfalse;
    return vresult;
}


static VALUE
_wrap_wxFrame_IsMaximized(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    bool result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    result = (bool)((wxFrame const *)arg1)->IsMaximized();
    
    vresult = result ? Qtrue : Qfalse;
    return vresult;
}


static VALUE
_wrap_wxFrame_Maximize(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    bool arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    arg2 = RTEST(argv[0]);
    (arg1)->Maximize(arg2);
    
    return Qnil;
}


static VALUE
_wrap_wxFrame_OnCreateStatusBar(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    int arg2 ;
    long arg3 ;
    wxWindowID arg4 ;
    wxString *arg5 = 0 ;
    wxStatusBar *result;
    Swig::Director *director = 0;
    VALUE vresult = Qnil;
    
    if ((argc < 4) || (argc > 4))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 4)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    arg2 = NUM2INT(argv[0]);
    arg3 = NUM2LONG(argv[1]);
    arg4 = NUM2INT(argv[2]);
    {
        arg5 = new wxString(STR2CSTR(argv[3]));
    }
    director = dynamic_cast<Swig::Director *>(arg1);
    if (director && (director->swig_get_self() == self)) director->swig_set_up();
    result = (wxStatusBar *)(arg1)->OnCreateStatusBar(arg2,arg3,arg4,(wxString const &)*arg5);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_wxStatusBar,0);
    return vresult;
}


static VALUE
_wrap_wxFrame_OnCreateToolBar(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    long arg2 ;
    wxWindowID arg3 ;
    wxString *arg4 = 0 ;
    wxToolBar *result;
    Swig::Director *director = 0;
    VALUE vresult = Qnil;
    
    if ((argc < 3) || (argc > 3))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 3)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    arg2 = NUM2LONG(argv[0]);
    arg3 = NUM2INT(argv[1]);
    {
        arg4 = new wxString(STR2CSTR(argv[2]));
    }
    director = dynamic_cast<Swig::Director *>(arg1);
    if (director && (director->swig_get_self() == self)) director->swig_set_up();
    result = (wxToolBar *)(arg1)->OnCreateToolBar(arg2,arg3,(wxString const &)*arg4);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_wxToolBar,0);
    return vresult;
}


static VALUE
_wrap_wxFrame_SendSizeEvent(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    (arg1)->SendSizeEvent();
    
    return Qnil;
}


static VALUE
_wrap_wxFrame_SetIcon(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    wxIcon *arg2 = 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    SWIG_ConvertPtr(argv[0], (void **) &arg2, SWIGTYPE_p_wxIcon, 1); if (arg2 == NULL) rb_raise(rb_eTypeError, "null reference");
    (arg1)->SetIcon((wxIcon const &)*arg2);
    
    return Qnil;
}


static VALUE
_wrap_wxFrame_SetIcons(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    wxIconBundle *arg2 = 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    SWIG_ConvertPtr(argv[0], (void **) &arg2, SWIGTYPE_p_wxIconBundle, 1); if (arg2 == NULL) rb_raise(rb_eTypeError, "null reference");
    (arg1)->SetIcons((wxIconBundle const &)*arg2);
    
    return Qnil;
}


static VALUE
_wrap_wxFrame_SetMenuBar(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    wxMenuBar *arg2 = (wxMenuBar *) 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    SWIG_ConvertPtr(argv[0], (void **) &arg2, SWIGTYPE_p_wxMenuBar, 1);
    (arg1)->SetMenuBar(arg2);
    
    return Qnil;
}


static VALUE
_wrap_wxFrame_SetShape(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    wxRegion *arg2 = 0 ;
    bool result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    SWIG_ConvertPtr(argv[0], (void **) &arg2, SWIGTYPE_p_wxRegion, 1); if (arg2 == NULL) rb_raise(rb_eTypeError, "null reference");
    result = (bool)(arg1)->SetShape((wxRegion const &)*arg2);
    
    vresult = result ? Qtrue : Qfalse;
    return vresult;
}


static VALUE
_wrap_wxFrame_SetStatusBar(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    wxStatusBar *arg2 = (wxStatusBar *) 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    SWIG_ConvertPtr(argv[0], (void **) &arg2, SWIGTYPE_p_wxStatusBar, 1);
    (arg1)->SetStatusBar(arg2);
    
    return Qnil;
}


static VALUE
_wrap_wxFrame_SetStatusBarPane(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    arg2 = NUM2INT(argv[0]);
    (arg1)->SetStatusBarPane(arg2);
    
    return Qnil;
}


static VALUE
_wrap_wxFrame_SetStatusText(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    wxString *arg2 = 0 ;
    int arg3 = (int) 0 ;
    Swig::Director *director = 0;
    
    if ((argc < 1) || (argc > 2))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    {
        arg2 = new wxString(STR2CSTR(argv[0]));
    }
    if (argc > 1) {
        arg3 = NUM2INT(argv[1]);
    }
    director = dynamic_cast<Swig::Director *>(arg1);
    if (director && (director->swig_get_self() == self)) director->swig_set_up();
    (arg1)->SetStatusText((wxString const &)*arg2,arg3);
    
    return Qnil;
}


static VALUE
_wrap_wxFrame_SetStatusWidths(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    int arg2 ;
    int *arg3 = (int *) 0 ;
    Swig::Director *director = 0;
    
    if ((argc < 2) || (argc > 2))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 2)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    arg2 = NUM2INT(argv[0]);
    SWIG_ConvertPtr(argv[1], (void **) &arg3, SWIGTYPE_p_int, 1);
    director = dynamic_cast<Swig::Director *>(arg1);
    if (director && (director->swig_get_self() == self)) director->swig_set_up();
    (arg1)->SetStatusWidths(arg2,arg3);
    
    return Qnil;
}


static VALUE
_wrap_wxFrame_SetToolBar(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    wxToolBar *arg2 = (wxToolBar *) 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    SWIG_ConvertPtr(argv[0], (void **) &arg2, SWIGTYPE_p_wxToolBar, 1);
    (arg1)->SetToolBar(arg2);
    
    return Qnil;
}


static VALUE
_wrap_wxFrame_SetTitle(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    wxString *arg2 = 0 ;
    Swig::Director *director = 0;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    {
        arg2 = new wxString(STR2CSTR(argv[0]));
    }
    director = dynamic_cast<Swig::Director *>(arg1);
    if (director && (director->swig_get_self() == self)) director->swig_set_up();
    (arg1)->SetTitle((wxString const &)*arg2);
    
    return Qnil;
}


static VALUE
_wrap_wxFrame_ShowFullScreen(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    bool arg2 ;
    long arg3 = (long) wxFULLSCREEN_ALL ;
    bool result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 2))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    arg2 = RTEST(argv[0]);
    if (argc > 1) {
        arg3 = NUM2LONG(argv[1]);
    }
    result = (bool)(arg1)->ShowFullScreen(arg2,arg3);
    
    vresult = result ? Qtrue : Qfalse;
    return vresult;
}


static VALUE
_wrap_disown_wxFrame(int argc, VALUE *argv, VALUE self) {
    wxFrame *arg1 = (wxFrame *) 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(argv[0], (void **) &arg1, SWIGTYPE_p_wxFrame, 1);
    {
Swig::Director *director = (Swig::Director*)(arg1);
        if (director) director->swig_disown();
    }
    
    return Qnil;
}



/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static void *_p_wxFrameTo_p_wxWindow(void *x) {
    return (void *)((wxWindow *)  ((wxFrame *) x));
}
static swig_type_info _swigt__p_wxIcon[] = {{"_p_wxIcon", 0, "wxIcon *", 0},{"_p_wxIcon"},{0}};
static swig_type_info _swigt__p_wxSize[] = {{"_p_wxSize", 0, "wxSize *", 0},{"_p_wxSize"},{0}};
static swig_type_info _swigt__p_wxWindow[] = {{"_p_wxWindow", 0, "wxWindow *", 0},{"_p_wxWindow"},{"_p_wxFrame", _p_wxFrameTo_p_wxWindow},{0}};
static swig_type_info _swigt__p_wxString[] = {{"_p_wxString", 0, "wxString *", 0},{"_p_wxString"},{0}};
static swig_type_info _swigt__p_wxStatusBar[] = {{"_p_wxStatusBar", 0, "wxStatusBar *", 0},{"_p_wxStatusBar"},{0}};
static swig_type_info _swigt__p_wxFrame[] = {{"_p_wxFrame", 0, "wxFrame *", 0},{"_p_wxFrame"},{0}};
static swig_type_info _swigt__p_wxMenuBar[] = {{"_p_wxMenuBar", 0, "wxMenuBar *", 0},{"_p_wxMenuBar"},{0}};
static swig_type_info _swigt__p_wxRegion[] = {{"_p_wxRegion", 0, "wxRegion *", 0},{"_p_wxRegion"},{0}};
static swig_type_info _swigt__p_int[] = {{"_p_int", 0, "int *", 0},{"_p_int"},{0}};
static swig_type_info _swigt__p_wxToolBar[] = {{"_p_wxToolBar", 0, "wxToolBar *", 0},{"_p_wxToolBar"},{0}};
static swig_type_info _swigt__p_wxPoint[] = {{"_p_wxPoint", 0, "wxPoint *", 0},{"_p_wxPoint"},{0}};
static swig_type_info _swigt__p_wxIconBundle[] = {{"_p_wxIconBundle", 0, "wxIconBundle *", 0},{"_p_wxIconBundle"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_wxIcon, 
_swigt__p_wxSize, 
_swigt__p_wxWindow, 
_swigt__p_wxString, 
_swigt__p_wxStatusBar, 
_swigt__p_wxFrame, 
_swigt__p_wxMenuBar, 
_swigt__p_wxRegion, 
_swigt__p_int, 
_swigt__p_wxToolBar, 
_swigt__p_wxPoint, 
_swigt__p_wxIconBundle, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */


#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) Init_wxFrame(void) {
static bool initialized;
if(initialized) return;
initialized = true;
    int i;
    
    SWIG_InitRuntime();
mWxFrame = mWx;
    
    for (i = 0; swig_types_initial[i]; i++) {
        swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        SWIG_define_class(swig_types[i]);
    }
    
    rb_define_module_function(mWxFrame, "disown_wxFrame", VALUEFUNC(_wrap_disown_wxFrame), -1);
    
    extern void Init_wxWindow();
    Init_wxWindow();
    //extern swig_class cWxWindow;
    cWxFrame.klass = rb_define_class_under(mWxFrame, "Frame", cWxWindow.klass);
    SWIG_TypeClientData(SWIGTYPE_p_wxFrame, (void *) &cWxFrame);
    rb_define_alloc_func(cWxFrame.klass, _wrap_wxFrame_allocate);
    rb_define_method(cWxFrame.klass, "initialize", VALUEFUNC(_wrap_new_wxFrame), -1);
    rb_define_method(cWxFrame.klass, "centre", VALUEFUNC(_wrap_wxFrame_Centre), -1);
    rb_define_method(cWxFrame.klass, "command", VALUEFUNC(_wrap_wxFrame_Command), -1);
    rb_define_method(cWxFrame.klass, "create", VALUEFUNC(_wrap_wxFrame_Create), -1);
    rb_define_method(cWxFrame.klass, "create_status_bar", VALUEFUNC(_wrap_wxFrame_CreateStatusBar), -1);
    rb_define_method(cWxFrame.klass, "create_tool_bar", VALUEFUNC(_wrap_wxFrame_CreateToolBar), -1);
    rb_define_method(cWxFrame.klass, "get_client_area_origin", VALUEFUNC(_wrap_wxFrame_GetClientAreaOrigin), -1);
    rb_define_method(cWxFrame.klass, "get_menu_bar", VALUEFUNC(_wrap_wxFrame_GetMenuBar), -1);
    rb_define_method(cWxFrame.klass, "get_status_bar", VALUEFUNC(_wrap_wxFrame_GetStatusBar), -1);
    rb_define_method(cWxFrame.klass, "get_status_bar_pane", VALUEFUNC(_wrap_wxFrame_GetStatusBarPane), -1);
    rb_define_method(cWxFrame.klass, "get_title", VALUEFUNC(_wrap_wxFrame_GetTitle), -1);
    rb_define_method(cWxFrame.klass, "get_tool_bar", VALUEFUNC(_wrap_wxFrame_GetToolBar), -1);
    rb_define_method(cWxFrame.klass, "iconize", VALUEFUNC(_wrap_wxFrame_Iconize), -1);
    rb_define_method(cWxFrame.klass, "is_full_screen", VALUEFUNC(_wrap_wxFrame_IsFullScreen), -1);
    rb_define_method(cWxFrame.klass, "is_iconized", VALUEFUNC(_wrap_wxFrame_IsIconized), -1);
    rb_define_method(cWxFrame.klass, "is_maximized", VALUEFUNC(_wrap_wxFrame_IsMaximized), -1);
    rb_define_method(cWxFrame.klass, "maximize", VALUEFUNC(_wrap_wxFrame_Maximize), -1);
    rb_define_method(cWxFrame.klass, "on_create_status_bar", VALUEFUNC(_wrap_wxFrame_OnCreateStatusBar), -1);
    rb_define_method(cWxFrame.klass, "on_create_tool_bar", VALUEFUNC(_wrap_wxFrame_OnCreateToolBar), -1);
    rb_define_method(cWxFrame.klass, "send_size_event", VALUEFUNC(_wrap_wxFrame_SendSizeEvent), -1);
    rb_define_method(cWxFrame.klass, "set_icon", VALUEFUNC(_wrap_wxFrame_SetIcon), -1);
    rb_define_method(cWxFrame.klass, "set_icons", VALUEFUNC(_wrap_wxFrame_SetIcons), -1);
    rb_define_method(cWxFrame.klass, "set_menu_bar", VALUEFUNC(_wrap_wxFrame_SetMenuBar), -1);
    rb_define_method(cWxFrame.klass, "set_shape", VALUEFUNC(_wrap_wxFrame_SetShape), -1);
    rb_define_method(cWxFrame.klass, "set_status_bar", VALUEFUNC(_wrap_wxFrame_SetStatusBar), -1);
    rb_define_method(cWxFrame.klass, "set_status_bar_pane", VALUEFUNC(_wrap_wxFrame_SetStatusBarPane), -1);
    rb_define_method(cWxFrame.klass, "set_status_text", VALUEFUNC(_wrap_wxFrame_SetStatusText), -1);
    rb_define_method(cWxFrame.klass, "set_status_widths", VALUEFUNC(_wrap_wxFrame_SetStatusWidths), -1);
    rb_define_method(cWxFrame.klass, "set_tool_bar", VALUEFUNC(_wrap_wxFrame_SetToolBar), -1);
    rb_define_method(cWxFrame.klass, "set_title", VALUEFUNC(_wrap_wxFrame_SetTitle), -1);
    rb_define_method(cWxFrame.klass, "show_full_screen", VALUEFUNC(_wrap_wxFrame_ShowFullScreen), -1);
    cWxFrame.mark = 0;
    cWxFrame.destroy = (void (*)(void *)) free_wxFrame;
}

