/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxFrame_WRAP_H_
#define SWIG_WxFrame_WRAP_H_

class Swig::Director;


class SwigDirector_wxFrame : public wxFrame, public Swig::Director {

public:
    SwigDirector_wxFrame(VALUE self);
    SwigDirector_wxFrame(VALUE self, wxWindow *parent, wxWindowID id, wxString const &title, wxPoint const &pos = wxDefaultPosition, wxSize const &size = wxDefaultSize, long style = wxDEFAULT_FRAME_STYLE, wxString const &name = wxT("frame"));
    virtual void SetTitle(wxString const &title);
    virtual ~SwigDirector_wxFrame();
    virtual wxStatusBar *OnCreateStatusBar(int number, long style, wxWindowID id, wxString const &name);
    virtual wxStatusBar *CreateStatusBar(int number = 1, long style = 0, wxWindowID id = -1, wxString const &name = wxT("statusBar"));
    virtual wxToolBar *OnCreateToolBar(long style, wxWindowID id, wxString const &name);
    virtual wxToolBar *CreateToolBar(long style = wxNO_BORDER, wxWindowID id = -1, wxString const &name = wxT("toolBar"));
    virtual void SetStatusText(wxString const &text, int number = 0);
    virtual void SetStatusWidths(int n, int *widths);
};


#endif
