/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxGauge_WRAP_H_
#define SWIG_WxGauge_WRAP_H_

class Swig::Director;


class SwigDirector_wxGauge : public wxGauge, public Swig::Director {

public:
    SwigDirector_wxGauge(VALUE self);
    SwigDirector_wxGauge(VALUE self, wxWindow *parent, wxWindowID id, int range, wxPoint const &pos = wxDefaultPosition, wxSize const &size = wxDefaultSize, long style = wxGA_HORIZONTAL, wxValidator const &validator = wxDefaultValidator, wxString const &name = wxT("gauge"));
    virtual ~SwigDirector_wxGauge();
};


#endif
