/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxGrid_WRAP_H_
#define SWIG_WxGrid_WRAP_H_

class Swig::Director;


class SwigDirector_wxGrid : public wxGrid, public Swig::Director {

public:
    SwigDirector_wxGrid(VALUE self);
    SwigDirector_wxGrid(VALUE self, wxWindow *parent, wxWindowID id, wxPoint const &pos = wxDefaultPosition, wxSize const &size = wxDefaultSize, long style = wxWANTS_CHARS, wxString const &name = wxPanelNameStr);
    SwigDirector_wxGrid(VALUE self, wxWindow *parent, int x, int y, int w = -1, int h = -1, long style = wxWANTS_CHARS, wxString const &name = wxPanelNameStr);
    virtual ~SwigDirector_wxGrid();
    virtual void OnActivate(bool active);
};


#endif
