/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.22
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxMDIParentFrame_WRAP_H_
#define SWIG_WxMDIParentFrame_WRAP_H_

class Swig::Director;


class SwigDirector_wxMDIParentFrame : public wxMDIParentFrame, public Swig::Director {

public:
    SwigDirector_wxMDIParentFrame(VALUE self, bool disown = false);
    SwigDirector_wxMDIParentFrame(VALUE self, wxWindow *parent, wxWindowID id, wxString const &title, wxPoint const &pos = wxDefaultPosition, wxSize const &size = wxDefaultSize, long style = wxDEFAULT_FRAME_STYLE, wxString const &name = "frame", bool disown = false);
    virtual void GetClientSize(int *width, int *height) const;
    virtual wxToolBar *GetToolBar() const;
    virtual wxMDIClientWindow *OnCreateClient();
    virtual void SetToolBar(wxToolBar *toolbar);
};


#endif
