/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.22
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxPanel_WRAP_H_
#define SWIG_WxPanel_WRAP_H_

class Swig::Director;


class SwigDirector_wxPanel : public wxPanel, public Swig::Director {

public:
    SwigDirector_wxPanel(VALUE self, wxWindow *parent, wxWindowID id = -1, wxPoint const &pos = wxDefaultPosition, wxSize const &size = wxDefaultSize, long style = wxTAB_TRAVERSAL, wxString const &name = "panel", bool disown = false);
    virtual void OnSysColourChanged(wxSysColourChangedEvent &event);
};


#endif
