/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxProgressDialog_WRAP_H_
#define SWIG_WxProgressDialog_WRAP_H_

class Swig::Director;


class SwigDirector_wxProgressDialog : public wxProgressDialog, public Swig::Director {

public:
    SwigDirector_wxProgressDialog(VALUE self, wxString const &title, wxString const &message, int maximum = 100, wxWindow *parent = NULL, int style = wxPD_APP_MODAL|wxPD_AUTO_HIDE);
    virtual ~SwigDirector_wxProgressDialog();
    virtual bool Update(int value, wxString const &newmsg = wxEmptyString);
    virtual bool Show(bool show = true);
};


#endif
