/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.22
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxScrolledWindow_WRAP_H_
#define SWIG_WxScrolledWindow_WRAP_H_

class Swig::Director;


class SwigDirector_wxScrolledWindow : public wxScrolledWindow, public Swig::Director {

public:
    SwigDirector_wxScrolledWindow(VALUE self, bool disown = false);
    SwigDirector_wxScrolledWindow(VALUE self, wxWindow *parent, wxWindowID id = -1, wxPoint const &pos = wxDefaultPosition, wxSize const &size = wxDefaultSize, long style = wxHSCROLL, wxString const &name = wxT("scrolledWindow"), bool disown = false);
    virtual void OnDraw(wxDC &dc);
};


#endif
