/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxSizer_WRAP_H_
#define SWIG_WxSizer_WRAP_H_

class Swig::Director;


class SwigDirector_wxSizer : public wxSizer, public Swig::Director {

public:
    SwigDirector_wxSizer(VALUE self);
    virtual bool Detach(wxWindow *window);
    virtual bool Detach(wxSizer *sizer);
    virtual bool Detach(int index);
    virtual void DeleteWindows();
    virtual wxSizerItem *Insert(size_t index, wxSizerItem *item);
    virtual void Layout();
    virtual void Clear(bool delete_windows = false);
    virtual void ShowItems(bool show);
};


#endif
