/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxToggleButton_WRAP_H_
#define SWIG_WxToggleButton_WRAP_H_

class Swig::Director;


class SwigDirector_wxToggleButton : public wxToggleButton, public Swig::Director {

public:
    SwigDirector_wxToggleButton(VALUE self);
    SwigDirector_wxToggleButton(VALUE self, wxWindow *parent, wxWindowID id, wxString const &label, wxPoint const &pos = wxDefaultPosition, wxSize const &size = wxDefaultSize, long style = 0, wxValidator const &val = wxDefaultValidator, wxString const &name = wxT("checkBox"));
    virtual ~SwigDirector_wxToggleButton();
};


#endif
