/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.22
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_WxToolBar_WRAP_H_
#define SWIG_WxToolBar_WRAP_H_

class Swig::Director;


class SwigDirector_wxToolBar : public wxToolBar, public Swig::Director {

public:
    SwigDirector_wxToolBar(VALUE self, bool disown = false);
    SwigDirector_wxToolBar(VALUE self, wxWindow *parent, wxWindowID id, wxPoint const &pos = wxDefaultPosition, wxSize const &size = wxDefaultSize, long style = wxTB_HORIZONTAL, wxString const &name = wxPanelNameStr, bool disown = false);
    virtual void OnRightClick(int toolId, float x, float y);
    virtual void OnMouseEnter(int toolId);
    virtual bool OnLeftClick(int toolId, bool toggleDown);
};


#endif
